spring.application.name=RaceToBid

# Database Configuration
spring.datasource.url=${DB_URL}
spring.datasource.username=${DB_USERNAME}
spring.datasource.password=${DB_PASSWORD}
spring.datasource.driver-class-name=org.postgresql.Driver

# JPA Configuration
spring.jpa.hibernate.ddl-auto=update
spring.jpa.show-sql=true
spring.jpa.properties.hibernate.dialect=org.hibernate.dialect.PostgreSQLDialect
spring.jpa.properties.hibernate.format_sql=true

# JWT Configuration
# Base64 encoded secret key
# Generate with: openssl rand -base64 32
jwt.secret=${JWT_SECRET}
jwt.refresh=${JWT_REFRESH}

# Server Configuration
server.port=8082

# Logging Configuration
logging.level.org.springframework.security=WARN
logging.level.org.springframework.web=WARN
logging.level.org.springframework.boot.autoconfigure=WARN
logging.level.org.racetobid=DEBUG
logging.level.io.opentelemetry=DEBUG
logging.level.io.micrometer=DEBUG


management.opentelemetry.resource-attributes.service.name=RaceToBid
management.opentelemetry.resource-attributes.service.version=0.0.1

# Tracing Configuration
management.tracing.enabled=true
management.tracing.sampling.probability=1.0
management.otlp.tracing.endpoint=http://localhost:4318/v1/traces
management.otlp.tracing.transport=http

# Metrics Configuration
management.otlp.metrics.export.url=http://localhost:4318/v1/metrics

# Logs Configuration
management.opentelemetry.logging.export.otlp.endpoint=http://localhost:4318/v1/logs

# Actuator: expose tracing endpoints
management.endpoints.web.exposure.include=health,info,metrics,prometheus
management.endpoint.health.show-details=always
